server:
  port: 80

spring:
  application:
    name: edge-service
  
  cloud:
    gateway:
      # default-filters:
      #   - SaveSession
      routes:
        - id: instrument-route
          uri: ${INSTRUMENT_SERVICE_URL:http://localhost:8181}
          predicates:
            - Host={tenant}.rock
            - Path=/instruments/**
          filters:
            - AddRequestHeader=X-Tenant-Id,{tenant}
        - id: instrument-route-v2
          uri: ${INSTRUMENT_SERVICE_URL:http://localhost:8181}
          predicates:
            - Host={tenant}.rock
            - Path=/instrumentsEdge/**
          filters:
            - AddRequestHeader=X-Tenant-Id,{tenant}
            - RewritePath=/instrumentsEdge/(?<segment>.*),/instruments/$\{segment}
            - RewritePath=/instrumentsEdge,/instruments
        - id: instrument-route-v3
          uri: ${INSTRUMENT_SERVICE_URL:http://localhost:8181}
          predicates:
            - Host={tenant}.rocks
            - Path=/instruments/**
          filters:
            - AddRequestHeader=X-Tenant-Id,{tenant}
        - id: instrument-route-v4
          uri: ${INSTRUMENT_SERVICE_URL:http://localhost:8181}
          predicates:
            - Host={tenant}.rocks
            - Path=/instrumentsEdge/**
          filters:
            - AddRequestHeader=X-Tenant-Id,{tenant}
            - RewritePath=/instrumentsEdge/(?<segment>.*),/instruments/$\{segment}
            - RewritePath=/instrumentsEdge,/instruments
logging:
  level: 
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    com.thomasvitale.edgeservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
