services:
  multitenant-db:
    image: "postgres:latest"
    container_name: "multitenant-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${MULTITENANT_DB_USER}
      - POSTGRES_PASSWORD=${MULTITENANT_DB_PASSWORD}
      - POSTGRES_DB=${MULTITENANT_DB}
      - TZ=Asia/Taipei
    ports:
      - "5432:5432"
    volumes:
      - multitenant-db-data:/var/lib/postgresql/data
    networks:
      - lab-network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev --import-realm --metrics-enabled=true
    volumes:
      - ./platform/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME_PATH=/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false      
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=auth
      - KC_HTTP_PORT=8080
      - TZ=Asia/Taipei
      - KC_HTTPS_PORT=8443
      - KC_CACHE_METRICS_HISTOGRAMS_ENABLED=true
      - KC_HTTP_METRICS_HISTOGRAMS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      # If you want to use a proxyto https , set the following environment variables
      #- KC_PROXY=edge
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - lab-network  


volumes:
  multitenant-db-data: { }

networks:
  lab-network:
    name: my-lab-network
